export const catalogGroups = [
  { category: "Perfumes", base: 25000, step: 7000, description: "A considered fragrance for the moments that stay with you.", names: "Lagos After Dark Eau de Parfum|Rose Silk Eau de Parfum|Sable Oud Eau de Parfum|Gold Coast Neroli Eau de Parfum|Amber Muse Eau de Parfum|Fig and Suede Eau de Parfum|Orchid No. 7 Eau de Parfum|Velvet Iris Eau de Parfum|Saffron Dusk Eau de Parfum|Citrus Veil Eau de Parfum|Jasmine Tide Eau de Parfum|Noir 24 Eau de Parfum|Peony Cloud Eau de Parfum|Cedar Bloom Eau de Parfum|Blush Hour Eau de Parfum" },
  { category: "Diffusers", base: 17000, step: 4500, description: "A slow, even release of scent to make a room feel like yours.", names: "Santal Reed Diffuser|Blush Peony Reed Diffuser|Lagos Rain Reed Diffuser|Amber and Oud Reed Diffuser|White Tea Reed Diffuser|Neroli Bloom Reed Diffuser|Midnight Fig Reed Diffuser|Cedar House Reed Diffuser|Vanilla Suede Reed Diffuser|Rosewater Reed Diffuser|Citrus Grove Reed Diffuser|Jasmine Linen Reed Diffuser|Saffron Rose Reed Diffuser|Sea Salt Reed Diffuser|Velvet Woods Reed Diffuser" },
  { category: "Humidifiers", base: 28000, step: 8000, description: "A quiet companion for softer air and a more comfortable space.", names: "Cloudmist Mini Humidifier|Halo Ultrasonic Humidifier|Aura Ceramic Humidifier|Still Air Humidifier|Dewdrop Desk Humidifier|Luma Night Humidifier|Serene Room Humidifier|Breeze Glass Humidifier|Mira Portable Humidifier|Avenue Smart Humidifier|Bloom Mist Humidifier|Contour Cool Mist Humidifier|Noma Travel Humidifier|Velvet Air Humidifier|Solace Large Room Humidifier" },
  { category: "Aromatics", base: 6500, step: 2500, description: "An atmospheric detail to turn an ordinary ritual into a lovely one.", names: "Still Life Candle|Rose and Oud Soy Candle|Lagos Morning Room Spray|Santal Incense Cones|White Tea Essential Oil|Amber Evening Candle|Peony Linen Mist|Cedarwood Incense Sticks|Neroli Wax Melts|Vanilla Orchid Candle|Sea Salt Room Spray|Jasmine Essential Oil|Fig and Amber Sachet|Blush Rose Candle|Soft Cotton Pillow Mist" },
  { category: "Furniture", base: 95000, step: 18000, description: "A beautiful foundation for a home that feels entirely your own.", names: "Arc Lounge Chair|Soma Accent Chair|Marlow Side Table|Noma Oak Bench|Aster Coffee Table|Elara Dining Chair|Sable Bedside Table|Solace Ottoman|Dune Console Table|Vela Bar Stool|Mira Nesting Tables|Cove Reading Chair|Palisade Bookshelf|Aura Entry Bench|Luma Dining Table" },
  { category: "Lighting", base: 24000, step: 8000, description: "Warm, considered light for evenings that deserve to linger.", names: "Solstice Table Lamp|Halo Bedside Lamp|Mira Pendant Light|Aura Wall Sconce|Dusk Floor Lamp|Noma Reading Lamp|Blush Glass Lamp|Cove Desk Lamp|Luma Ceramic Lamp|Sable Pendant Light|Dawn Linen Shade Lamp|Aster Brass Sconce|Velvet Glow Lamp|Elara Lantern Lamp|Still Night Light" },
  { category: "Objects", base: 12000, step: 3000, description: "An expressive object that gives everyday corners a little more character.", names: "Forma Ceramic Vase|Noma Stoneware Bowl|Sable Marble Tray|Blush Bud Vase|Arc Sculptural Object|Elara Glass Vessel|Mira Catchall Dish|Aster Bookends|Dune Terracotta Planter|Cove Serving Board|Luma Brass Bowl|Velvet Trinket Box|Solace Tall Vase|Dawn Ceramic Pitcher|Halo Table Sculpture" },
  { category: "Textiles", base: 18000, step: 5000, description: "A soft layer to bring warmth, texture, and ease into the everyday.", names: "Sunday Throw|Blush Linen Cushion|Noma Woven Rug|Velvet Rose Cushion|Aster Cotton Blanket|Dune Table Runner|Mira Linen Napkins|Cove Knit Throw|Sable Jacquard Cushion|Elara Bath Towel Set|Solace Boucle Cushion|Dawn Linen Duvet|Halo Waffle Throw|Aura Cotton Rug|Luma Bedspread" },
  { category: "Accessories", base: 10000, step: 3000, description: "A considered companion for the beautiful things you carry every day.", names: "Everyday Tote|Blush Travel Pouch|Sable Leather Wallet|Mira Canvas Shopper|Noma Jewellery Case|Aster Weekend Bag|Cove Cosmetic Pouch|Dune Card Holder|Velvet Hair Scarf|Luma Sunglass Case|Elara Key Charm|Solace Tech Sleeve|Aura Mini Crossbody|Dawn Toiletry Bag|Halo Travel Organiser" },
] as const;
